// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeuWO5HWVx1GFQZGz-fqqnGd8H0fRcKw',
    appId: '1:165741973057:android:1dd1e84438a5a5a9d080c0',
    messagingSenderId: '165741973057',
    projectId: 'todoist-aeea7',
    storageBucket: 'todoist-aeea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMJOLjdV-UANZu3ACm5sy15EAIT7xxpS8',
    appId: '1:165741973057:ios:7695bff47a372acdd080c0',
    messagingSenderId: '165741973057',
    projectId: 'todoist-aeea7',
    storageBucket: 'todoist-aeea7.appspot.com',
    androidClientId: '165741973057-i9hrv0jbb20jlnfuau2vr117mt3mpne8.apps.googleusercontent.com',
    iosClientId: '165741973057-705aq0e80hehneu28ptncajb1gjoqap1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoist_firebase',
  );

}